name: hop_topic
description: Hop Colony topics
version: 0.0.6
repository: https://github.com/hopcolony/flutter-hopcolony

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stomp_dart_client: ^0.4.1
  hop_init: ^0.0.4
  logging: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter