name: hop_auth
description: Hop Colony auth
version: 0.0.9
repository: https://github.com/hopcolony/flutter-hopcolony

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4
  shared_preferences: ^2.0.5

  hop_init: ^0.0.4
  hop_doc: ^0.0.4
  hop_topic: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter