name: hop_drive
description: Hop Colony Drive
version: 0.0.2
repository: https://github.com/hopcolony/flutter-hopcolony

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^5.1.0
  image: ^3.0.2
  dio: ^3.0.10
  uuid: ^3.0.4
  crypto: ^3.0.1
  convert: ^3.0.0
  hop_init: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter