name: hop_doc
description: Hop Colony Docs
version: 0.0.5
repository: https://github.com/hopcolony/flutter-hopcolony

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  hop_init: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter