name: hop_doc
description: A Flutter library for Hop Doc
version: 0.0.2
author: Luis Paarup

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  websocket: ^0.0.5

  hop_init:
    git: 
      url: git@gitlab.com:Paarup/hopcolony-flutter.git
      path: packages/hop_init
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter