name: hop_init
description: Hop Colony Init
version: 0.0.4
repository: https://github.com/hopcolony/flutter-hopcolony

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter